---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torchserve-ai-algo-cfs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: torchserve-ai-algo-cfs-pvc
    namespace: ai-algo
  mountOptions:
  - hard
  - nfsvers=3
  - nolock
  nfs:
    path: /g97mfuca/
    server: 10.8.50.49
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cbs
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torchserve-ai-algo-cfs-pvc
  namespace: ai-algo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
  volumeMode: Filesystem
  volumeName: torchserve-ai-algo-cfs-pv

